development:
  adapter: postgresql
  encoding: unicode
  database: gmail_passbook_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gmail_passbook_test
  pool: 5
  host: localhost

#production:
#  adapter: postgresql
#  database: bucket
#  username: bucket
#  password: theBucket
#  #adapter: sqlite3
#  #database: db/production.sqlite3
#  #pool: 5
#  #timeout: 5000
